# name: Deploy API

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Deploy to server
#       run: |
#         ssh user@your-server-ip << 'EOF'
#         cd /chemin/vers/le/projet
#         git pull origin main
#         pip install -r requirements.txt
#         systemctl restart gunicorn
#         EOF
